spring:
  application:
    name: my_ribbon

# notice: can NOT use job_app as name
job-app:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8092,localhost:8093
    ServerListRefreshInterval: 15000

server:
  port: 8084