spring:
  cloud:
    gateway:
#      routes:
#        - id: myRouteA
#          uri: http://localhost:8081
#          predicates:
#            - Path=/order_app_http/**
#          filters:
#            - StripPrefix=1
#        - id: myRouteB
#          uri: lb://order.app
#          predicates:
#            - Path=/order_app_lb/**
#          filters:
#            - StripPrefix=1
#        - id: myRouteC
#          uri: lb://spring-cloud-producer
#          predicates:
#            - Path=/spring_cloud_producer_lb/**
#          filters:
#            - StripPrefix=1
      discovery:
        locator:
          enabled: true
        httpclient:
          ssl:
            useInsecureTrustManager: false

